import React from 'react'

const about = () => {
  return (
    <div>
      about
    </div>
  )
}

export default about

export const metadata = {
    title: "about facebook title",
    description: "Generated by create next app",
  };