



export const metadata = {
  title: "facebook connect wid ur frnds Create Next App",
  description: "face is ok Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div>
        <span>Admin navbar</span>
    </div>
  );
}
